### ISSUE TITLE
Sobrescrita indevida de conteúdo do array no construtor da classe Troco

### ISSUE THREAD

**Issue by JoaoDias-223** [JoaoDias-223/ticket-machine#17]
O array `papeisMoeda` tem seu segundo elemento sobrescrito indevidamente devido à uma constante durante seu acesso.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/63318342/191377102-4bdb5a71-7b6d-4cbb-82c7-b2bae1642159.png">

**Comment by antuniooh** [comment]
Issue duplicada, acabei escrevendo uma igual -> https://github.com/JoaoDias-223/ticket-machine/issues/25

Estou encerrando esta.
