### ISSUE TITLE
Use case CSU02 não possui passo de débito do saldo

### ISSUE THREAD

**Issue by JoaoDias-223** [JoaoDias-223/ticket-machine#7]
O _use case_ CSU02 não possui um passo para debitar do saldo o valor do bilhete. Nesse caso, é necessário adicionar essa mudança à documentação.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/63318342/191370159-f62b4ca3-1d1b-4107-8102-f44f98783960.png">

**Comment by antuniooh** [comment]
Dado que isso se refere a um ajuste de doc, não é possivel criar uma branch para isolar o ajuste. 

Desse modo o ajuste será feito na página referente ao fluxo principal do usecase CSU02, adicionando um novo passo após a emissao do bilhete.

Gerando:


| Ações do Ator                                             | Ações do Sistema                                             |
|-----------------------------------------------------------|--------------------------------------------------------------|
| 1. O Cliente solicita impressão do bilhete de transporte. |                                                              |
|                                                           | 2. O Sistema verifica o saldo e emite o bilhete              |
|                                                           | 3. O sistema debita o valor do bilhete do saldo.             |
|                                                           | 3. O sistema informa o saldo atual. Caso de Uso é encerrado. |
